title:  Readiness Quiz - Introduction to the Unix Shell 
description: This quiz tests your knowledge of basic UNIX shell commands, including file navigation and management.  
theme: null 
markdown: kramdown 
kramdown: 
  input: GFM 